<script type="text/javascript">
<?php
$baseUrl = Zend_Controller_Front::getInstance()->getRequest()->getBaseUrl();
$qrUploadUrl = $this->dbtable->qruploadkey_value ? Zend_Controller_Front::getInstance()->getRequest()->getScheme().'://'.Zend_Controller_Front::getInstance()->getRequest()->getHttpHost().$baseUrl.'/utils/qrupload/'.$this->dbtable->qruploadkey_value : ""
?>
var fileUploadLimit = '<?php echo Zend_Registry::get('config')->max_file_upload_size;?>';
var numAttachedDocs = <?php echo count($this->dbtable->document_ids);?>;
var qrUploadUrl = "<?php echo $qrUploadUrl;?>";
$(document).ready(function () {
    $("textarea[name='comment_text']").focus();
});
</script>


<?php

$title = $this->dbtable->is_fieldcomment ? 'Add Attachment(s) and Caption' : 'Edit Comment';
$linkified_title = $title;

$this->layout()->title = $title;
$this->layout()->setLayout('layoutdialog');
$this->layout()->scrollhold = true;
$this->layout()->scrollholdkey = $this->dbtable->getTableName();


$buttons = array();
if (Zend_Registry::get('customAcl')->isAllowed($_SESSION['account']->getRole(), 'table:'.$this->dbtable->getTableName(), 'edit')
                && !$this->dbtable->isEditOperationBlocked('save', $this->dbtable->getTableName())) {
    $buttons[] = '<input class="bd-button" type="submit" value="Save" name="btnOK">';
    $buttons[] = '<input id="CancelBtnID" class="bd-button" type="submit" value="Cancel" name="btnCancel">';
} else {
    $buttons[] = '<input class="bd-button" type="submit" value="Close" name="btnCancel">';
}

$html = '';
$html .= '
        <h1 class="dialogtitle">'.$linkified_title.'</h1>';

$html .= $this->dbtable->fetchHiddenTableAndIndexFormTags();
if ($this->edit_buffer_key) {
    $html .= '<input type="hidden" name="edit_buffer_key" value="'.$this->edit_buffer_key.'">';
}
$html .= '<input type="hidden" name="qruploadkey_value" value="'.$this->dbtable->qruploadkey_value.'">';
$html .= '<input type="hidden" name="btnOnChange" value="">';
$html .= '<input type="hidden" name="onChangeParams" value="">';   // if btnOnChange is set, this is sometimes used for params
$html .= '<input type="hidden" name="btnAddIncomingJoin" value="">'; // set this to join name to add an incoming join record
$html .= '<input type="hidden" name="btnDeleteIncomingJoin" value="">'; // set this to join name to delete an incoming join record
$html .= '<input type="hidden" name="btnSubEditParams" value="">'; // when calling a subpage will look like table=grades&grade_id=3 for example

$html .= '<p><table class="edittable"><colgroup>
                        <col class="table_label_width">
                        <col class="table_value_width">
                        <col class="table_label_width">
                        <col class="table_value_width"></colgroup>';

// don't show fields as editable if editing of this record is not allowed
$editable = Zend_Registry::get('customAcl')->isAllowed($_SESSION['account']->getRole(), 'table:'.$this->dbtable->getTableName(), 'edit')
    && !$this->dbtable->isEditOperationBlocked('save', $this->dbtable->getTableName());

$fieldlayout = array();
if ($_SESSION['account']->getRole()=='DataTerminal') {
    $fieldlayout[] = array(  array('dbfield' => 'user_id'));
}
if (!$this->dbtable->is_fieldcomment || AdminSettings::getInstance()->edit_comment_data) {
    $this->dbtable->setFieldAttribute('comment_added', 'caption', 'Effective Date');
    $fieldlayout[] = array(array('dbfield' => 'comment_added'));
}
if (AdminSettings::getInstance()->edit_comment_data) {
    $fieldlayout[] = array(  array('dbfield' => 'itemobject_id'));
}

$subcaption = '<a href="#" class="a_pop_link">tips</a>
                        <div style="display:none;">
                        '.DBTableRowComment::commentTipsHtml().'
                        </div>';
$input_rows = 8;
if ($this->dbtable->is_fieldcomment) {
    $this->dbtable->setFieldAttribute('comment_text', 'caption','Caption');
    $input_rows = 4;
    $subcaption = '(optional)';
}

$fieldlayout[] = array(array('dbfield' => 'comment_text', 'field_attributes' => array('input_cols' => 70, 'input_rows' => $input_rows, 'subcaption' => $subcaption)));
$html .= fetchEditTableTR($fieldlayout, $this->dbtable, '', $editable);
$html .= '</table></p>
            ';

$html .= '<p>'.implode('&nbsp;', $buttons).'</p>';
$html .= '<h2 class="bd-edit-page-headers">Documents / Photos</h2>';
$html .= '<div id="documentsEditorDiv" class="bd-edit-block"></div>';

echo '  <div class="dialogbody">
        '.fetch_form_tag('
                            <div class="dialogcontent">'.$html.'
                            </div>
        ').'
    </div>';
?>

<!-- The file upload form used as target for the file upload widget -->
<form id="fileupload" action="//dummydomain.com/" method="POST" enctype="multipart/form-data">
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
        <div class="span7">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="icon-plus icon-white"></i>
                <span>Add Files...</span>
                <input type="file" name="files[]" multiple>
            </span>

        </div>
        <!-- The global progress information -->
        <div class="fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="bar" style="width:0%;"></div>
            </div>
            <!-- The extended global progress information -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <div class="qrwrapper"><div><ul style="margin-left: -25px; margin-top:0px; margin-bottom: 0px; font-weight: bold;"><li>Drag and Drop Files Here or</li><li>Scan this Code with Your Mobile Device</ul></div>
    <div id="updatebannerId" class="qrupload_comm_banner" style="display:none;">Connected</div>
    <div style="margin-top:10px;" id="qrcode"></div></div>
    <!-- The loading indicator is shown during file processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files" data-toggle="modal-gallery" data-target="#modal-gallery"></tbody></table>
</form>


<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-upload fade">
        <td class="preview"><span class="fade"></span></td>
        <td class="name"><span>{%=file.name%}</span></td>
        <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
        {% if (file.error) { %}
            <td class="error" colspan="2"><span class="label label-important">Error</span> {%=file.error%}</td>
        {% } else if (o.files.valid && !i) { %}
            <td>
                <div class="progress progress-success progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="bar" style="width:0%;"></div></div>
            </td>
            <td class="start">{% if (!o.options.autoUpload) { %}
                <button class="btn btn-primary">
                    <i class="icon-upload icon-white"></i>
                    <span>Start</span>
                </button>
            {% } %}</td>
        {% } else { %}
            <td colspan="2"></td>
        {% } %}
        <td class="cancel">{% if (!i) { %}
            <button class="btn btn-warning">
                <i class="icon-ban-circle icon-white"></i>
                <span>Cancel</span>
            </button>
        {% } %}</td>
    </tr>
{% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
{% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        {% if (file.error) { %}
            <td></td>
            <td class="name"><span>{%=file.name%}</span></td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td class="error" colspan="2"><span class="label label-important">Error</span> {%=file.error%}</td>
        {% } else { %}
            <td class="preview">{% if (file.thumbnail_url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" data-dialog download="{%=file.name%}"><img src="{%=file.thumbnail_url%}"></a>
            {% } %}</td>
            <td class="name">
                <a href="{%=file.url%}" title="{%=file.name%}" data-gallery="{%=file.thumbnail_url&&'gallery'%}" download="{%=file.name%}">{%=file.name%}</a>
            </td>
            <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
            <td colspan="2"></td>
        {% } %}
        <td class="delete">
            <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"{% if (file.delete_with_credentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                <i class="icon-trash icon-white"></i>
                <span>Delete</span>
            </button>

        </td>
    </tr>
{% } %}
</script>
<!-- The Templates plugin is included to render the upload/download listings -->
<script src="<?php echo $baseUrl;?>/jqueryextras/js/tmpl.js"></script>
<!-- The Load Image plugin is included for the preview images and image resizing functionality -->
<script src="<?php echo $baseUrl;?>/jqueryextras/js/load-image.js"></script>
<!-- The Canvas to Blob plugin is included for image resizing functionality -->
<script src="<?php echo $baseUrl;?>/jqueryextras/js/canvas-to-blob.js"></script>
<!-- The Iframe Transport is required for browsers without support for XHR file uploads -->
<script src="<?php echo $baseUrl;?>/jqueryextras/jquery-file-upload/js/jquery.iframe-transport.js"></script>
<!-- The basic File Upload plugin -->
<script src="<?php echo $baseUrl;?>/jqueryextras/jquery-file-upload/js/jquery.fileupload.js"></script>
<!-- The File Upload file processing plugin -->
<script src="<?php echo $baseUrl;?>/jqueryextras/jquery-file-upload/js/jquery.fileupload-fp.js"></script>
<!-- The File Upload user interface plugin -->
<script src="<?php echo $baseUrl;?>/jqueryextras/jquery-file-upload/js/jquery.fileupload-ui.js"></script>
<!-- The File Upload jQuery UI plugin -->
<script src="<?php echo $baseUrl;?>/jqueryextras/jquery-file-upload/js/jquery.fileupload-jui.js"></script>
<script language="JavaScript" src="<?php echo $baseUrl;?>/scripts/struct/commenteditview.js?v=15" type="TEXT/JAVASCRIPT"></script>


<!-- The XDomainRequest Transport is included for cross-domain file deletion for IE8+ -->
<!--[if gte IE 8]><script src="js/cors/jquery.xdr-transport.js"></script><![endif]-->
<!-- The dialog widget -->
<div id="blueimp-gallery-dialog" data-show="fade" data-hide="fade">
    <!-- The gallery widget  -->
    <div class="blueimp-gallery blueimp-gallery-carousel blueimp-gallery-controls"  data-transition-speed=100>
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
</div>
<script src="<?php echo $baseUrl;?>/jqueryextras/gallery-2.15.2/js/blueimp-gallery.min.js"></script>
<script src="<?php echo $baseUrl;?>/jqueryextras/image-gallery/js/jquery.image-gallery.custom.js"></script>
