<?php
    $this->layout()->title = 'Help';
    $this->layout()->setLayout('layoutpopup');
    require_once('markdown.php');
    
    $html = '';
    
    
    $html .= '<div id="helpBody">';
    $html .= Markdown($this->help_obj->help_markup);
    $html .= '</div>';

    $html .= '<p>';
    $html .= '<button class="bd-button" type="button" onclick="window.close();">Close</button>';
    $html .= '</p>';
    echo fetch_form_tag($html);    
?>
