<?php
	$this->layout()->title = 'Change Account Password';
	$this->layout()->setLayout('layoutdialog');
        
	$html = '<table class="edittable">
                  '.($this->fields['user_cryptpassword'] ? '<tr> 
                    <th>Current Password:</th>
                    <td><input type="password" name="currentpassword" value="'.htmlentities($this->fields['currentpassword']).'" size="50"></td>
                  </tr>' : '').'
                  <tr> 
                    <th>New Password:</th>
                    <td><input type="password" name="password" value="'.htmlentities($this->fields['password']).'" size="50"></td>
                  </tr>
                  <tr> 
                    <th>Verify New Password:</th>
                    <td><input type="password" name="password2" value="'.htmlentities($this->fields['password2']).'" size="50"></td>
                  </tr>
                </table>';
        echo fetch_edit_page($this->layout()->title,$html);
        
?>

