<?php
$this->layout()->title = 'Change Temporary Password';
$this->layout()->setLayout('layoutdialog');

$html = '<table class="edittable">
		<tr>
		<th>New Password:</th>
		<td><input type="password" name="password" value="'.htmlentities(isset($this->fields['password']) ? $this->fields['password'] : '').'" size="50"></td>
				</tr>
				<tr>
				<th>Verify New Password:</th>
				<td><input type="password" name="password2" value="'.htmlentities(isset($this->fields['password2']) ? $this->fields['password2'] : '').'" size="50"></td>
						</tr>
						</table>';
echo fetch_form_page($this->layout()->title,$html, array('OK' => 'btnOK', 'Cancel' => 'btnDoNothing'));