<?php

$this->layout()->title = 'Password Reset Request';
$this->layout()->setLayout('layoutdialog');
$html = '<p style="width:400px;">If you can\'t remember your password, you will need a new one.  To obtain a new one, you need to know your Login ID.</p>';
$html .= '<p style="margin-top:20px;">Enter your <b>Login ID</b>:</p>';
$html .= '<p class="name_search_box"><input style="width:400px;" name="login_id" id="login_id" value="'.$_SESSION['resetmypassword']['login_id'].'"></p>';


echo fetch_form_page($this->layout()->title,$html,array('OK' => 'btnOK', 'Cancel' => 'btnCancel'));
