<?php $baseUrl = Zend_Controller_Front::getInstance()->getRequest()->getBaseUrl();?>
<script language="JavaScript" src="<?php echo $baseUrl;?>/scripts/user/resetpassword.js?v=2" type="TEXT/JAVASCRIPT"></script>

<?php

$this->layout()->title = $this->formtable->is_new_user ? 'Set Password' : 'Reset Password';
$this->layout()->setLayout('layoutdialog');

$warn_about_user = Zend_Registry::get('config')->allowed_to_keep_temp_pw ? 'If yes, the user will be offered a chance (but not forced) to change it when they log in.' : 'If yes, the user will be forced to change it when they log in.';
$this->formtable->setFieldAttribute('has_temporary_password', 'subcaption', $warn_about_user);
if ($this->formtable->is_new_user) {
    $this->formtable->setFieldAttribute('email_password', 'caption', 'Email the username and password to the user');
}
$html = '';
$html .= '<table class="edittable"><colgroup>
             <col class="table_label_width">
             <col class="short_table_value_width">
             <col class="table_label_width">
             <col class="short_table_value_width"></colgroup>';

$html .= fetchEditTableTR(array(array('password'),array('password2')), $this->formtable);
$html .= fetchEditTableTR(array(array('has_temporary_password'),array('email_password'),array('email'),array('message')), $this->formtable);
$html .= '</table>';

echo fetch_form_page($this->layout()->title, $html, array('OK' => 'btnOK', 'Cancel' => 'btnCancel'));
