<?php

$this->layout()->title = 'Password Reset Request';
$this->layout()->setLayout('layoutdialog');
$html = '';

$html .= '<p>Hello <b>'.$this->dbtable->fullName(true).'</b>,</p>';

if ($this->dbtable->email) {
	$html .= "<p style=\"width:400px;\">If your correct email address is <b>'{$this->dbtable->email}'</b> and you can read email at this address, click this button to automatically reset your password and mail it to you:</p>";
	$html .= '<input class="bd-button" type="submit" name="btnResetByEmail" value="Automatically Email Me a New Password"/>';
}

$preface = $this->dbtable->email ? "Alternatively, you" : "You don't have an email address entered in the system.  However, you";

$html .= '<p style="margin-top:40px; width:400px;">'.$preface.' can ask an administrator to reset your password.<br /><b>How should the adminstrator contact you with your new password?</b>:<br />
   <input style="width:400px;" name="contact_location" id="contact_location" value="'.$_SESSION['resetmypassword']['contact_location'].'"><br />(alternate email address, phone number, physical location, etc.)</p>';

echo fetch_form_page($this->layout()->title,$html,array('Reset My Password and Contact Me' => 'btnRequestResetFromAdmin', 'Cancel' => 'btnCancel'));
